name: scamurai
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  appwrite: ^14.0.0
  get: ^4.7.2
  shared_preferences: ^2.5.2
  image_picker: ^1.1.2
  android_intent_plus: ^5.3.0
  file_picker: ^9.0.2
  share_handler: ^0.0.22
  dio: ^5.8.0+1
  flutter_markdown: ^0.7.6+2
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
